- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create directory app
  ansible.builtin.file:
    path: /app
    state: directory

# - name: "Download the {{component}} application"
#   ansible.builtin.get_url:
#     url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
#     dest: /tmp

- name: Download the artifact from nexus
  ansible.builtin.get_url:
    url: "{{NEXUS_URL}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.{{extension}}"
    dest: /tmp

- name: "Unzip {{component}}.zip to /app directory"
  ansible.builtin.unarchive:
    src: "/tmp/{{component}}-{{app_version}}.{{extension}}"
    dest: /app
    remote_src: yes